# Generated by Django 2.1.1 on 2022-03-03 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contact_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='deposit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
