# Generated by Django 2.1.1 on 2022-03-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contact_deposit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
    ]
