# Generated by Django 2.1.1 on 2022-03-03 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20220303_2310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Paypal',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='account_balance',
            new_name='available_balance',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='username',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='active_deposit',
            new_name='downlines',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='bonus_balance',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='last_deposit',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='last_withdrawal',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='pending_withdrawal',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='profit_balance',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='total_balance',
        ),
        migrations.AddField(
            model_name='balance',
            name='deposit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
