# Generated by Django 2.1.1 on 2022-03-04 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20220303_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('wallet', models.TextField(max_length=100)),
                ('method', models.TextField(max_length=100)),
                ('withdrawal_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('username', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Bitcoin',
        ),
    ]
