# Generated by Django 2.1.1 on 2022-03-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='0', max_length=200),
        ),
    ]
