# Generated by Django 2.1.1 on 2022-03-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20220304_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, default='processing', max_length=100),
        ),
    ]
